apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: default
data:
  NODE_ENV: "production"
  PORT: "8080"
  DB_HOST: "logicmatrix-db-prod.c123456789.us-east-1.rds.amazonaws.com"
  DB_PORT: "5432"
  DB_NAME: "logicmatrixdb"
  DB_USER: "matrixadmin"
